### ISSUE TITLE
Add command for testing in README

### ISSUE THREAD

**Issue by kimmichurri** [kimmichurri/FE-Palette-Picker#27]
**Is your feature request related to a problem? Please describe.**
`npm test -- --coverage` does not work for generating a coverage report
`npm t -- --coverage --watchAll=false` does work. Let's add that to our README

**Describe the solution you'd like**
We want any developer who clones down the repo to be able to successfully run a test coverage report

**Comment by jessicalyn** [comment]
Added to readme!
